# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b78160345fdeb178449b47b60ff538ff6ed7eb32270d928897fbf874917815f68e131b3836ca18194fc9dfd3c22094606b377bfadfb28e049839b819f754564

test:
  secret_key_base: f0bfb596141e756357a9bade5979e0a5e314ce9a3b5aaa66fe647c749501a87b5501c89a5819845ad3074ec6556210e2f63d1a871982a4ab89d48f83220e1b45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
